apiVersion: apps/v1
kind: Deployment
metadata:
  name: fibonacci-frontend-deployment
  labels:
    app: fibonacci
    tier: frontend
  annotations:
    kubernetes.io/change-cause: Fibonacci-frontend-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fibonacci
      tier: frontend
  template:
    metadata:
      labels:
        app: fibonacci
        tier: frontend
    spec:
      containers:
      - name: fibonacci-frontend
        image: oshokry/fibonacci-frontend
        env:
        - name: PASS_PHRASE
          valueFrom:
            secretKeyRef:
              name: passphrase-secret
              key: passphrase
---
apiVersion: v1
kind: Service
metadata:
  name: fibonacci-frontend-nps
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30099
  selector:
      app: fibonacci
      tier: frontend
